### ISSUE TITLE
Bower usage

### ISSUE THREAD

**Issue by Grawl** [outpunk/evil-icons#15]
NPM usage is so hardcore for me and my static site generator on Grunt. Will be good to add “bower-style” instruction on how to use all these great things. Because now I just dunno what to do with all these SVG's. Have I pack them into font? Or pack into one SVG with `all.svg#target`-style using?

**Comment by outpunk** [comment]
Hi, guys. We’ve decided to implement more useful features first. And bower is at the end of that list, sorry.

Instead, I recommend you to use our plugins for [Gulp] and [Grunt] or the NPM package.
[Gulp]: https://github.com/outpunk/gulp-evil-icons
[Grunt]: https://github.com/outpunk/grunt-evil-icons

**Comment by Grawl** [comment]
Okay

**Comment by yoghi** [comment]
Gulp and Grunt aren't package manager. This choice force user to generate every time the icons.

**Comment by outpunk** [comment]
Bower is just a packages downloader, it doesn't provide any tools to use the helpers. Using helpers is the main reason why we're wrapping the icons into packages. If we had wanted to use bare svg files, we would have done the icons as a common zip archive.
