### ISSUE TITLE
Player controls

### ISSUE THREAD

**Issue by alexander-irbis** [outpunk/evil-icons#40]
* play
* pause
* stop
* fastforward
* rewind

There are already ei-play, but one is not typical for player controls

**Comment by romashamin** [comment]
@alexander-irbis I am not planning to include pause/stop/etc icons into the core set, because creating a custom video player is not a frequent task. Most developers prefer to use embedded video.

**Comment by Jabher** [comment]
+1
I know, it's closed, but I would be really happy to see "play", "pause" and "next" icons.
