### ISSUE TITLE
Text editor controls

### ISSUE THREAD

**Issue by alexander-irbis** [outpunk/evil-icons#41]
* bold
* italic
* underline
* strikeout
* quote
* superscript
* subscript
* paragraph
* header
* ordered list
* unordered list
* blockquote
* indent
* inindent
* align left
* align center
* align right
* justify
* align top
* align middle
* align bottom
* text color
* background color
* font size
* font bigger
* font smaller
* image resize
* clear
* create
* save
* copy
* cut
* paste

Some inspiration can be found here: http://fontawesome.io/icons/#text-editor

**Comment by romashamin** [comment]
The [same reason]: creating text editors is not a frequent task.

[same reason]: https://github.com/outpunk/evil-icons/issues/40
