### ISSUE TITLE
Rake tasks fails due to external JS processor

### ISSUE THREAD

**Issue by yurijmi** [outpunk/evil-icons#53]
I use Ruby 2.2.0 with Node.js on Mac OS X 10.9.5 and building sprites (```evil_icons:process```) fails:
```You're using ExecJS::ExternalRuntime, did you forget to add therubyracer or other execjs runtime to gemfile?```

Solution is to add a development dependency ```therubyracer```. Fixed in #54

**Comment by outpunk** [comment]
ExecJS not required, we use Node.
