### ISSUE TITLE
Multiple custom classes

### ISSUE THREAD

**Issue by andy-saint** [outpunk/evil-icons#57]
Is it possible to add more than 1 custom class? I'm currently using 'circle white bg-black' (from the basscss framework) but it's only outputting 'circle'.

**Comment by outpunk** [comment]
Which method do you use? Could you provide a code example, please?

**Comment by andy-saint** [comment]
I'm using gulp-evil-icons

Gulp task

```js
gulp.task('views', function() {
  return gulp.src('app/*.jade')
    .pipe($.jade({
      pretty: true
    }))
    .pipe($.evilIcons())
    .pipe(gulp.dest('dist'));
});
```

Jade file

```jade
icon(name='ei-cart' size='l' class='circle white bg-black')
```

I've tried it using just raw HTML too but get the same output (only the 'circle' class comes through).

**Comment by outpunk** [comment]
It seems like a bug. I can't fix it right now, but I'll do that in a couple of days.

**Comment by outpunk** [comment]
@andy-saint Hello, the fixed versions of `evil-icons` and `gulp-evil-icons` is in npm. Thank you for the report!
