### ISSUE TITLE
Message with badge icon

### ISSUE THREAD

**Issue by barsukov** [outpunk/evil-icons#58]
Probably I did not find it, and it was already there. 
But it would be awesome to see message Icon with badge, and how it possible to use for example twitter bootsrap badge with current message icon?

**Comment by romashamin** [comment]
@barsukov if you are asking for a solid message-and-badge icon, I’m not sure it is a good idea.

I offer you to take `ei-envelope` and combine it with `<span class="badge">42</span>` from Twitter Bootstrap.

**Comment by barsukov** [comment]
Thank you for answer. I expect to see something like this but with your icon )
![screenshot 2015-04-28 09 44 20](https://cloud.githubusercontent.com/assets/1594996/7364864/7f4cb416-ed8b-11e4-8a1e-846acb797e3c.png)

**Comment by romashamin** [comment]
@barsukov → http://codepen.io/anon/pen/xGbJjW

![ei-envelope-badge](https://cloud.githubusercontent.com/assets/1148914/7366186/0fc90ffe-ed9f-11e4-8e5e-3b6a319ba7a2.png)
P. S. I suppose using absolute position is a bit stupid, but enough for the example.

**Comment by barsukov** [comment]
@romashamin THX! :+1:
