### ISSUE TITLE
Browserify compatibility 

### ISSUE THREAD

**Issue by bravedick** [outpunk/evil-icons#60]
fs can't be accessed using browserify's require: http://stackoverflow.com/questions/24999068/browserify-error-uncaught-typeerror-undefined-is-not-a-function

And it works ok something like this:

`var spritePath  = 'assets/sprite.svg';
var sprite      = spritePath.toString();`

Other small fixes:
1. `var options = options || {};` == ` options = options || {};` (options already exists)
2. remove `.sass-cache` folder

**Comment by outpunk** [comment]
Thank you for the report. It seems like we're not gonna support browserify — I'm working on the custom icons feature right now. And the feature heavily relies on the file system. Instead, I recommend you to use the CDN version or `assets/evil-icons.min.js` directly if you want to include the icons in your JS.
