### ISSUE TITLE
Unable to use JQuery click functions.

### ISSUE THREAD

**Issue by uplusion23** [outpunk/evil-icons#65]
I've tried a lot to get a click event to fire. Nothing has worked.

**Comment by outpunk** [comment]
Which element do you listen on?

**Comment by uplusion23** [comment]
I've tried SVG, USE, .icon, and .ei-[iconname]. No avail sadly.

**Comment by outpunk** [comment]
It works http://codepen.io/anon/pen/Pqdvgj

**Comment by outpunk** [comment]
Thank you for the report. Released the new version.
