### ISSUE TITLE
Update Google+ logo

### ISSUE THREAD

**Issue by romashamin** [outpunk/evil-icons#70]
See more: https://developers.google.com/+/branding-guidelines

**Comment by romashamin** [comment]
/cc @xnutsive
![em-emoji-tbi 2x](https://cloud.githubusercontent.com/assets/1148914/10262585/ef881514-69d6-11e5-9d2a-5a2d7d7ccfe4.png)

**Comment by xnutsive** [comment]
Wow. So thank you, much awesome, very gratitude.
