### ISSUE TITLE
Font format

### ISSUE THREAD

**Issue by mdcanham** [outpunk/evil-icons#73]
This is probably more of a question than an issue/feature request. Is there a way to load evil icons as a font into our HTML?

**Comment by outpunk** [comment]
Sorry, but no. 

It's the worst what can be done with Evil Icons for several reasons:
1. Icons are not graphemes, they require more precise rendering which can't be achieved with a font.
2. With font we can't color an icon using more than one color.
3. It's impossible to make responsive icons with font.
4. Font for icons is a hack and we have less hacky ways to load icons.

Also, we're going to implement dynamic sprite building which can't be done with font.
