### ISSUE TITLE
Middleman 3.4.1 can't find evil-icons

### ISSUE THREAD

**Issue by tlindsay** [outpunk/evil-icons#77]
I'm getting a Sprockets error when I try to `require evil-icons` in my styles.scss. It happens both when I serve (via pow.cx and Anvil) and when I try to build:
```
/Users/Pat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:106:in `resolve': couldn't find file 'evil-icons' (Sprockets::FileNotFound)
  (in /Users/Pat/Developer/Make/thatdarnpat/source/stylesheets/styles.scss:9)
	from /Users/Pat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sprockets-2.12.4/lib/sprockets/context.rb:146:in `require_asset'
```
I believe I've installed everything correctly:
```bash
$ bundle show middleman
/Users/Pat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-3.4.1
$ bundle show evil_icons
/Users/Pat/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/evil_icons-1.8.0
```

`config.rb` has no problems requiring `evil_icons`. If I take the `require` out of my SCSS and leave it in `config.rb`, then nobody complains. The helper also seems to be injecting SVGs into my markup correctly.

**Comment by outpunk** [comment]
Please try to add the `css` extension: `//= require evil-icons.css`. Hope, this will work.

**Comment by tlindsay** [comment]
No dice :disappointed:
Same error as before.

**Comment by outpunk** [comment]
Could you make a minimal example and show me?

**Comment by tlindsay** [comment]
https://github.com/tlindsay/middleman-test

The only things I changed from default are adding `gem 'sass'` and `gem 'evil_icons'` to Gemfile, `//= require evil-icons` in all.scss, and I added a `config.ru` so I can serve with pow.cx.

**Comment by outpunk** [comment]
@iiska did you encounter this problem?

**Comment by iiska** [comment]
@outpunk No I didn't. But I could take a look and compare that example to my middleman site if I could find root cause that way.

**Comment by outpunk** [comment]
@tlindsay you have to add the following to your `config.rb`:
```ruby
require "evil_icons"
helpers EvilIcons::Helpers

after_configuration do
  sprockets.append_path(EvilIcons.assets_dir)
end
```

**Comment by outpunk** [comment]
@iiska nevermind, I've found the problem. Thank you for the involvement.

**Comment by tlindsay** [comment]
@outpunk Yeah, that fixed it! Is mine a special case, or do the docs need to be updated?

**Comment by tlindsay** [comment]
Oh! I see you already updated them. Sorry! 

Thanks for your help!

**Comment by outpunk** [comment]
Great! You're welcome :)
