### ISSUE TITLE
Google Chrome 49 bug

### ISSUE THREAD

**Issue by tab** [outpunk/evil-icons#80]
After update Google Chrome 49.0.2623.75 (64-bit) stable version which was released yesterday I saw bug with evil-icons: in my rails 4.2 application I have two pages: landing and auth, on landing page evil-icons works perfectly and on auth page I can't see them.
In previous version I have not had such problems with evil-icons.

Live example:
landing with icons on footer - https://foodiegram.ru 
auth icons doesn't visible - https://foodiegram.ru/auth

In other browsers everything works as usual. 

rails 4.2.5.2
evil_icons 1.8.0

Thanks for help.

**Comment by outpunk** [comment]
Will investigate, thank you for the report.

**Comment by tab** [comment]
I found a problem: in my layout a have an `<base href="/">` for angular html5 mode.

After I removed `<base href="/">` and replace

`$locationProvider.html5Mode(true)`

with

```
$locationProvider.html5Mode
  enabled: true
  requireBase: false
```

evil-icons appears.
